// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/service.proto

package example

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	drawer "github.com/ponteilla/protoc-gen-twirp_typescript/protobuf/drawer"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hat struct {
	Size                 int32                      `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Color                string                     `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Name                 string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ribons               []*Ribon                   `protobuf:"bytes,4,rep,name=ribons,proto3" json:"ribons,omitempty"`
	Plume                map[string]*drawer.Feather `protobuf:"bytes,5,rep,name=plume,proto3" json:"plume,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp       `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cc183e5db670d0, []int{0}
}

func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (m *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(m, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hat) GetRibons() []*Ribon {
	if m != nil {
		return m.Ribons
	}
	return nil
}

func (m *Hat) GetPlume() map[string]*drawer.Feather {
	if m != nil {
		return m.Plume
	}
	return nil
}

func (m *Hat) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cc183e5db670d0, []int{1}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

type Ribon struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ribon) Reset()         { *m = Ribon{} }
func (m *Ribon) String() string { return proto.CompactTextString(m) }
func (*Ribon) ProtoMessage()    {}
func (*Ribon) Descriptor() ([]byte, []int) {
	return fileDescriptor_45cc183e5db670d0, []int{2}
}

func (m *Ribon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ribon.Unmarshal(m, b)
}
func (m *Ribon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ribon.Marshal(b, m, deterministic)
}
func (m *Ribon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ribon.Merge(m, src)
}
func (m *Ribon) XXX_Size() int {
	return xxx_messageInfo_Ribon.Size(m)
}
func (m *Ribon) XXX_DiscardUnknown() {
	xxx_messageInfo_Ribon.DiscardUnknown(m)
}

var xxx_messageInfo_Ribon proto.InternalMessageInfo

func (m *Ribon) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func init() {
	proto.RegisterType((*Hat)(nil), "example.Hat")
	proto.RegisterMapType((map[string]*drawer.Feather)(nil), "example.Hat.PlumeEntry")
	proto.RegisterType((*Size)(nil), "example.Size")
	proto.RegisterType((*Ribon)(nil), "example.Ribon")
}

func init() { proto.RegisterFile("example/service.proto", fileDescriptor_45cc183e5db670d0) }

var fileDescriptor_45cc183e5db670d0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x5f, 0x8b, 0xd4, 0x30,
	0x14, 0xc5, 0xe9, 0xcc, 0x74, 0x96, 0xbd, 0xf5, 0x1f, 0x61, 0xd5, 0x52, 0x50, 0xcb, 0x80, 0x4b,
	0x5f, 0x26, 0x85, 0x8a, 0xa0, 0xee, 0x9b, 0xa0, 0x8c, 0x0f, 0x82, 0x44, 0x9f, 0x7c, 0x91, 0xb4,
	0x7b, 0xb7, 0x0d, 0xdb, 0x34, 0x25, 0x49, 0xf7, 0x8f, 0x1f, 0xc7, 0x4f, 0x2a, 0x49, 0xba, 0x33,
	0xf3, 0x76, 0x73, 0xee, 0xe1, 0x90, 0xf3, 0xbb, 0xf0, 0x1c, 0xef, 0xb8, 0x1c, 0x7b, 0x2c, 0x0d,
	0xea, 0x1b, 0xd1, 0x20, 0x1d, 0xb5, 0xb2, 0x8a, 0x9c, 0xcc, 0x72, 0xf6, 0xa6, 0x55, 0xaa, 0xed,
	0xb1, 0xf4, 0x72, 0x3d, 0x5d, 0x95, 0xbf, 0x84, 0x44, 0x63, 0xb9, 0x1c, 0x83, 0x33, 0x3b, 0xbb,
	0xd4, 0xfc, 0x16, 0x75, 0x79, 0x85, 0xdc, 0x76, 0xa8, 0x83, 0xba, 0xf9, 0xb7, 0x80, 0xe5, 0x8e,
	0x5b, 0x42, 0x60, 0x65, 0xc4, 0x5f, 0x4c, 0xa3, 0x3c, 0x2a, 0x62, 0xe6, 0x67, 0x72, 0x06, 0x71,
	0xa3, 0x7a, 0xa5, 0xd3, 0x45, 0x1e, 0x15, 0xa7, 0x2c, 0x3c, 0x9c, 0x73, 0xe0, 0x12, 0xd3, 0xa5,
	0x17, 0xfd, 0x4c, 0xce, 0x61, 0xad, 0x45, 0xad, 0x06, 0x93, 0xae, 0xf2, 0x65, 0x91, 0x54, 0x4f,
	0xe8, 0xfc, 0x2d, 0xca, 0x9c, 0xcc, 0xe6, 0x2d, 0xd9, 0x42, 0x3c, 0xf6, 0x93, 0xc4, 0x34, 0xf6,
	0xb6, 0x97, 0x7b, 0xdb, 0x8e, 0x5b, 0xfa, 0xc3, 0x6d, 0xbe, 0x0c, 0x56, 0xdf, 0xb3, 0xe0, 0x22,
	0x17, 0x90, 0x34, 0x1a, 0xb9, 0xc5, 0x3f, 0x56, 0x48, 0x4c, 0xd7, 0x79, 0x54, 0x24, 0x55, 0x46,
	0x43, 0x53, 0xfa, 0xd0, 0x94, 0xee, 0x9b, 0x32, 0x08, 0x76, 0x27, 0x64, 0xdf, 0x00, 0x0e, 0x89,
	0xe4, 0x19, 0x2c, 0xaf, 0xf1, 0xde, 0xd7, 0x3b, 0x65, 0x6e, 0x24, 0x6f, 0x21, 0xbe, 0xe1, 0xfd,
	0x84, 0xbe, 0x5d, 0x52, 0x3d, 0xa5, 0x81, 0x0f, 0xfd, 0x1a, 0xf8, 0xb0, 0xb0, 0xfd, 0xb4, 0xf8,
	0x10, 0x6d, 0x5e, 0xc3, 0xea, 0xa7, 0x03, 0xf2, 0x02, 0xd6, 0x62, 0x68, 0x3a, 0x34, 0x33, 0xa6,
	0xf9, 0xb5, 0x79, 0x05, 0xb1, 0xef, 0x79, 0x20, 0x16, 0x1d, 0x11, 0xab, 0xde, 0x43, 0xb2, 0xe3,
	0x35, 0xea, 0x4b, 0x6e, 0x3a, 0xd4, 0xe4, 0x1c, 0x4e, 0xbe, 0xf3, 0x6b, 0x74, 0xd4, 0x1f, 0xef,
	0x01, 0xb8, 0xfc, 0xec, 0xd1, 0x31, 0x8f, 0xcf, 0x17, 0xbf, 0x3f, 0xb6, 0xc2, 0x76, 0x53, 0x4d,
	0x1b, 0x25, 0x4b, 0xc3, 0x45, 0x2f, 0xd1, 0x6a, 0x71, 0x17, 0x4e, 0xdc, 0x6c, 0x5b, 0x1c, 0xb6,
	0xf6, 0x56, 0xe8, 0xd1, 0x9a, 0xc3, 0xd5, 0xe7, 0x80, 0x7a, 0xed, 0x95, 0x77, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x38, 0x54, 0x62, 0x0e, 0x37, 0x02, 0x00, 0x00,
}
